install: /usr/include/freetype /usr/include/ft2build.h
	yay -S --needed polybar
/usr/include/freetype:
	ln -s /usr/include/freetype2/freetype $@
/usr/include/ft2build.h:
	ln -s /usr/include/freetype2/ft2build.h $@
